### ISSUE TITLE
[Suggestion] Some sort of button to toggle the power state for the Drawbridge Block.

### ISSUE THREAD

**Issue by SonicX8000** [MC-U-Team/Draw-Bridge#1]
By default, the drawbridge block is 'off' and needs a redstone signal in order to place the blocks. Could there be some sort of button to invert the block's power state?

Like... for example... if you turn it's power state to 'on'... it'll place the blocks as if it had a redstone signal, however if you give it a redstone signal while it's 'on'... it'll turns off and put away the blocks.

I guess you could call it a 'Inverted Drawbridge Block' in a way.

**Comment by MrTroble** [comment]
This is a good idea. I will add it asap!

Cheers
~MrTroble

**Comment by HyCraftHD** [comment]
Is it better to make a whole new block or just an option in the tileentity (gui) block to invert it?

**Comment by MrTroble** [comment]
I would make a Button.

**Comment by SonicX8000** [comment]
At first I was going to suggest a new block but then thought that when you put the blocks inside it... it'll auto-place them right away. You can delay it via the tick slider but figure the gui button toggle might be better.

It's kinda like the Resonant Servo block from Thermal Dynamics where it has 3 states of redstone control, Ignored, Low & High. Drawbridge button toggle would be Low & High which Low is ON and turns off if powered while High is OFF which turns on if powered.

**Comment by MrTroble** [comment]
Feature tested and committed! Will be included in the next version

Thanks for the enhancement
Cheers
~MrTroble

**Comment by HyCraftHD** [comment]
Release is now on curseforge
