### ISSUE TITLE
[1.14.4] Drawbridge Render as non-full block

### ISSUE THREAD

**Issue by NielsPilgaard** [MC-U-Team/Draw-Bridge#10]
**Describe the bug**
using the drawerbridge, there is a slot for the block to render as another to blend in with the rest of your base, but as you can see if its not a full block it allows x-ray

Additionally, placing a complex block as the render block can crash you - It does with a Wire from the mod Silent Mechanisms. Crash-report at the bottom.

**To Reproduce**
1. Place Drawbridge
2. Give it a torch as a render item
3. See-through drawbridge

**Expected behavior**
For the Drawbridge to reject/not accept the item, or otherwise indicate that it should not be used. Maybe default to normal Drawbridge render.

**Screenshots**
[Screenshot](https://cdn.discordapp.com/attachments/611984629896839188/632612575418515466/2019-10-12_17.15.52.png)

**Versions**
- Minecraft Version 1.14.4
- Forge Version 28.1.39
- UTeamCore Version 1.14.4-2.7.4.134

**Log (if crash occures)**
https://gist.github.com/NillerMedDild/9bbd31a0abf3aeea8374d42927659342

**Comment by MrTroble** [comment]
This shouldn't happen as you shouldn't be able to put in a torch in the first place in the first place.
I am investigating this.

Cheers
~MrTroble

**Comment by HyCraftHD** [comment]
This is a bug, that I have cause by not checking for the right properties.
Currently we only check if the block is solid:
https://github.com/MC-U-Team/Draw-Bridge/blob/9812869a8d9939065c310c81a2f8b060f488f0d6/src/main/java/info/u_team/draw_bridge/tileentity/DrawBridgeTileEntity.java#L35-L42
This check is not enough. Dunno which method is better suited here.

**Comment by MrTroble** [comment]
I have already thought that this was an issue ... gonna change that

**Comment by MrTroble** [comment]
This should be fixed by now ... if this should reoccur please reopen
