### ISSUE TITLE
[1.14.4] Issue with optifine

### ISSUE THREAD

**Issue by HyCraftHD** [MC-U-Team/Draw-Bridge#11]
**Describe the bug**
Crash when starting with optifine

**To Reproduce**
1. Download optifine
2. Start minecraft
3. Crash when starting

**Expected behavior**
Should start.

**Versions**
- Minecraft Version: 1.14.4
- Forge Version: 28.1.61
- UTeamCore Version: 2.7.4.134
- Mod Version: 1.2.2.10
- Optfine Version: 1.14.4 HD U F4

**Log (if crash occures)**
https://gist.github.com/HyCraftHD/d77afe2bb191e571d60a809f9510beae

**Comment by MrTroble** [comment]
This is referring to https://github.com/MC-U-Team/Draw-Bridge/blob/2a48b92b7450833686e5447980bfea661619b01a/src/main/java/info/u_team/draw_bridge/init/DrawBridgeModels.java#L24

location is probably somehow null. I'd go for a simple null check here

**Comment by MrTroble** [comment]
It is not even loading optifine for me lul

**Comment by HyCraftHD** [comment]
http://optifine.net/adloadx?f=OptiFine_1.14.4_HD_U_F4.jar This version?
Or this: http://optifine.net/adloadx?f=preview_OptiFine_1.14.2_HD_U_F1_pre15.jar?

**Comment by MrTroble** [comment]
The F4 version

**Comment by HyCraftHD** [comment]
Well, maybe try the preview. It worked for me some time ago

**Comment by MrTroble** [comment]
Gonna go down F3 to the preview builds

**Comment by MrTroble** [comment]
It is loading F3 with a warning

**Comment by sepsol** [comment]
They pulled their preview builds but I have used some and they worked fine (namely OptiFine 1.14.4 HD U F4 pre 4 through 11). I'll send you a download link [here ](https://www.dropbox.com/sh/bogdw5xrx9u6c6d/AACUT_lagrcYwjASYrRTw28oa?dl=0)for the time-being until they release a stable version. It is safe, I guarantee .

**Comment by MrTroble** [comment]
thank you for the download link I will go and check it out

**Comment by MrTroble** [comment]
May I ask which forge version you used?

**Comment by sepsol** [comment]
I was on 28.1.61 and the final releases didn't work. I tried 28.1.70 and the latest stable OptiFine (F4) and they worked fine though. Either one of these should work, give it a try.

**Comment by MrTroble** [comment]
I have the bad feeling that I am doing something wrong here.

**Comment by MrTroble** [comment]
OK never mind it did work.

**Comment by sepsol** [comment]
Glad it helped ;)

**Comment by MrTroble** [comment]
Yeah man thx.
