### ISSUE TITLE
Request: Set drawbridge height/length

### ISSUE THREAD

**Issue by Discomanco** [MC-U-Team/Draw-Bridge#14]
Request to set how many blocks it should access, instead of always using all 10 blocks with the last air ones

**Comment by MrTroble** [comment]
actually this shouldn't replace anything with air tbh

**Comment by MrTroble** [comment]
this bug is tied to #15

**Comment by HyCraftHD** [comment]
Is kinda fixed with #15
The length is currently not configurable, but might be in 1.15.1.
