### ISSUE TITLE
[1.14.4] Blocks already in the range are consumed

### ISSUE THREAD

**Issue by Discomanco** [MC-U-Team/Draw-Bridge#15]
**Describe the bug**
When you extend the Draw Bridge, blocks that are already in its extension area are simply consumed. It seems to have a low chance to add those back to the inventory

**To Reproduce**
1. Place down Draw Bridge
2. Place 1 item in the first slot
3. Place 1-9 blocks in the world, in front of the Draw Bridge
4. Power Draw Bridge
5. De-power Draw Bridge
6. All blocks you placed are likely gone now. Not in the inventory of the Draw Bridge, nor will push out again when powering it

**Expected behavior**
To either ignore blocks it didn't place (preferred, goes well with #14 too), or add those picked up blocks to its inventory.

**Screenshots**

**Versions**
- Minecraft Version 1.14.4
- Forge Version 28.1.69
- UTeamCore Version 2.7.5.135-SNAPSHOT

**Comment by MrTroble** [comment]
Thanks for your reports I will try to fix it asap

Cheers
~MrTroble

**Comment by Eonasdan** [comment]
this also appears in the 1.12.2 version.

I have a setup like this. Where `>/<` is drawbridge, `=` is iron bars, and `|` is a wall. The right side bridges will suck bars through the wall.
```
>===|===<
>===|===<
>===|===<
```

**Comment by MrTroble** [comment]
Hello and also Thanks,

I am currently not able to fix anything of it. I am very sorry, I will fix things as soon as there is some time in sight.

Cheers
~MrTroble

**Comment by HyCraftHD** [comment]
This problem is fixed with [this](https://github.com/MC-U-Team/Draw-Bridge/commit/8b9fd894ac0f5b8b8facb0f761e4aa8515a524d7) commit and will be on curseforge soon.
The animation will be removed though.

**Comment by Eonasdan** [comment]
can you back port that fix to 1.12.2 please?

**Comment by HyCraftHD** [comment]
We'll see. 1.12.2 is currently not on my target list
