### ISSUE TITLE
1.15.2 Client crash when applying camouflage 

### ISSUE THREAD

**Issue by ClaudiusMinimus** [MC-U-Team/Draw-Bridge#19]
If I try to place a stone brick wall as the camouflage the client crashes. This also crashes any other players on our server who are in the same chunk.

**Expected behavior**
It would be nice if the drawbridge would prevent non-compatible blocks from being applied to the camouflage slot in the draw bridge block.

**Versions**
- Mod version: draw_bridge-1.15.2-1.4.3.18
- Minecraft version: 1.15.2
- Forge version: 31.1.88
- UTeamCore version: u_team_core-1.15.2-2.11.0.156.jar

https://paste.ee/p/24FNz
https://paste.ee/p/8HYxI

BTW: I love your mod!

**Comment by Knito58** [comment]
Yes exactly the same happened to us: Server is running, two clients crashed when I applied a yellow stone brick from pneumaticcraft as camouflage.
```

java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=x_part, clazz=class me.desht.pneumaticcraft.common.block.BlockPlasticBrick$PartType, values=[NONE, LEFT, RIGHT]} as it does not exist in Block{drawbridge:draw_bridge}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93) ~[?:?] {re:mixin,re:classloading}
... bla
```

**Comment by HyCraftHD** [comment]
Thanks for the report. Need to fix that soon
