### ISSUE TITLE
I can not disable the ore generation.

### ISSUE THREAD

**Issue by cursinorock** [MC-U-Team/Draw-Bridge#2]
I can not disable the ore generation.
I tried to change the settings in the config file but had no effect on the world generation.

**Comment by MrTroble** [comment]
This mod does not effect the world generation.
Maybe you mean our core mod the [U-Team-Core](https://github.com/MC-U-Team/U-Team-Core) ?

Cheers
~MrTroble

**Comment by cursinorock** [comment]
My Bad.
