### ISSUE TITLE
[1.12.2] Dupe glitch using pistons

### ISSUE THREAD

**Issue by TrevorBagels** [MC-U-Team/Draw-Bridge#20]
Basically, pistons can be used on a draw bridge to duplicate the blocks already in it. 
To reproduce, just place down a sticky piston, put a draw bridge block on the front of the piston, put some blocks into the draw bridge, and activate the piston. 
The blocks inside the draw bridge will come out of it as if it were being broken, and if you click on the drawbridge, the blocks will still be in there. 

Game version: 1.12.2
Mod version: 1.12.2-1.2.1.8

**Comment by HyCraftHD** [comment]
1.12.2 is outdated so this will not be fixed
