### ISSUE TITLE
Does not work in water

### ISSUE THREAD

**Issue by jedron215** [MC-U-Team/Draw-Bridge#3]
Drawbridge does not work in water. Only works with air.

(put here by mod maker's request. Thanks for making a great mod!)

**Comment by MrTroble** [comment]
Hello @jedron215 

I will add add support for water asap!

Cheers
~MrTroble

**Comment by MrTroble** [comment]
This has bin changed in 9367fc412f4100528a953b08517d9039640d8d09 !

Thanks for your feedback the changes will be applied in the next update on curseforge

Cheers
~MrTroble
