### ISSUE TITLE
[1.14.4] Crash when opening Draw Bridge

### ISSUE THREAD

**Issue by NielsPilgaard** [MC-U-Team/Draw-Bridge#7]
**Describe the bug**
I crashed directly after opening the GUI of a Drawbridge.

**To Reproduce**
1. Obtain Drawbridge
2. Place it
3. Open it

**Expected behavior**
The Drawbridge GUI to open.

**Screenshots**

**Versions**
- 1.14.4
- forge-1.14.4-28.1.20
- u_team_core-1.14.4-2.7.3.132
- draw_bridge-1.14.4-1.2.2.9

**Log (if crash occures)**
https://gist.github.com/NillerMedDild/2d9f4bccbfb58873ec022926df2de041

**Comment by HyCraftHD** [comment]
Thank you for the report.
This seems to be an obfuscation issue when implementing the IItemHandler and IInventory interface in one class.
https://github.com/MC-U-Team/Draw-Bridge/blob/4c0442fb2b1a1cc1918a8ebba81dfd34ee1811e6/src/main/java/info/u_team/draw_bridge/util/InventoryStackHandler.java#L38

Will fix that soon.
~Johanens

**Comment by NielsPilgaard** [comment]
Thanks for the fast response, I look forward to trying the mod out :D

**Comment by HyCraftHD** [comment]
Should be fixed in 1.14.4-1.2.2.10 which is now on curseforge. Thanks for the report 👍 
~Johannes

**Comment by NielsPilgaard** [comment]
Thank you! It works very well now.
