### ISSUE TITLE
Request - Sounds / Animation

### ISSUE THREAD

**Issue by NielsPilgaard** [MC-U-Team/Draw-Bridge#8]
Hi again o/

I would like to suggest that you add the placement sound of blocks that the Drawbridge places, when the Drawbridge is activated.

Additionally, and I know this is (also) a big suggestion, but a draw/retract animation would be really cool, to add a little extra flare.

I hope you'll consider it, and thank you for making the mod regardless :)

**Comment by HyCraftHD** [comment]
Thanks for the suggestions.
The sound is easy and was a plan in further updates. (Currently this is only a port of the 1.12.2 version)

Animations would be very cool but I don't really know how to do this in a performant way. @MrTroble Do you have an idea?

**Comment by MrTroble** [comment]
Possible, have to look into the block rendering system again ... I may have some time in the future to do so. Might be worth to look into pistons!

Cheers
~MrTroble

**Comment by MrTroble** [comment]
Update: Pistons seem to use a special render while extending. I will go for that too. This should be pretty doable.

**Comment by MrTroble** [comment]
So I made some progress. https://youtu.be/LJeQlTn-B_4 Looking good? Any feedback?

**Comment by NielsPilgaard** [comment]
That looks awesome! I would speed it up a bit though, maybe 1.25x.

**Comment by MrTroble** [comment]
The speed is actually determined by the speed the bridge is extending at. In other words you can modify the speed with the speed modifier in the GUI.

Cheers
~MrTroble

**Comment by NielsPilgaard** [comment]
Damn, great work! :D
Would it be possible to apply the smooth movement to the very first block as well? It looks like it just appears/disappears.

**Comment by MrTroble** [comment]
Yeah this is currently a problem in the backend I will try to rewrite this bits asap.
It is actually more work then I anticipated.

Cheers
~MrTroble

**Comment by MrTroble** [comment]
@HyCraftHD Ya wanna make sounds?

**Comment by HyCraftHD** [comment]
Im not sure what sound we should make. A continues sond when the drawbridge extracts or just a sound per block place?

**Comment by MrTroble** [comment]
A would suggest a continues sound as the animation is also continues. Any suggestions @NillerMedDild 

Cheers
~MrTroble

**Comment by NielsPilgaard** [comment]
I also think continuous sound would make the most sense. What about a continuous wire pulling sound, and when each block is fully placed, play the piston sound?

I hope you know what I mean by wire pulling sound, otherwise I'll try to find some reference material this evening :)

**Comment by MrTroble** [comment]
I would appreciate some reference sound tho.

Cheers
~MrTroble

**Comment by NielsPilgaard** [comment]
I couldn't find what I was thinking of, so... nevermind on the wire pulling sound :P

**Comment by MrTroble** [comment]
What in the world a we doing for sound then?

**Comment by HyCraftHD** [comment]
Well, I'll find something. But other question. Is your animation system now working without any bugs?

**Comment by MrTroble** [comment]
It is just not rendering the first one but besides the everything seems to be bugfree

**Comment by HyCraftHD** [comment]
Okay, can you fix that in reasonable time?
I'll then try to find a sound.

**Comment by MrTroble** [comment]
I will do it just now.

**Comment by MrTroble** [comment]
I have fixed an other round of bugs!
Sounds still missing

**Comment by MrTroble** [comment]
The new beta version should be on curseforge! Still missing sound tho
Thank you for your request. Please go check it out. I'd be happy to get some feedback on it :)

Cheers
~MrTroble

**Comment by NielsPilgaard** [comment]
I'll check it out right away, thanks :D

**Comment by NielsPilgaard** [comment]
It looks really great! I did find 2 things that made me go huh though:

* Drawbridges set to the same speed, triggered at the same time, will extend their blocks with a short delay. About 1 redstone tick between the Drawbridges as far as I can tell.
* Extending Iron Bars results in the Iron Bar collision box being the same as a full block. This is a really minor issue, just something I noticed.

**Comment by MrTroble** [comment]
ok the first one is weird. I know where the second one is coming from, this was done due to rendering issues. I will fix this asap

**Comment by MrTroble** [comment]
OK I found both issues and fixed them

**Comment by MrTroble** [comment]
An other release is out now!

**Comment by NielsPilgaard** [comment]
Thank you!

**Comment by HyCraftHD** [comment]
Because the animation introduced so many bugs and @MrTroble didn't have time to fix these the animation is removed in further builds

**Comment by NielsPilgaard** [comment]
Alright, fair enough.
